version: '3'
services:
  redmine:
    image: redmine
    ports:
      - 3000:3000
    environment:
      - REDMINE_DB_MYSQL=db
      - REDMINE_DB_PASSWORD=example
    depends_on:
      - db
    restart: always
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=redmine
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == worker

  logger:
    image: fluent/fluentd
    deploy:
      mode: global
    restart: always

  portainer_master:
    image: portainer/portainer
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.name == manager-node
